{{- $name:= printf "%s-svc.%s.svc" (include "acjs.fullname" .) $.Release.Namespace -}}
{{- $cert := genSelfSignedCert ( include "acjs.fullname" $ ) nil ( list $name ) 14600 -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "acjs.fullname" . }}-secret
  labels:
    {{- include "acjs.labels" . | nindent 4 }}
data:
  acjs.crt: {{ $cert.Cert | b64enc }}
  acjs.key: {{ $cert.Key | b64enc }}

---

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: "{{ $name }}"
webhooks:
- name: "{{ $name }}"
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["CREATE"]
    resources:   ["pods"]
    scope:       "Namespaced"
  clientConfig:
    service:
      namespace: {{ $.Release.Namespace }}
      name: {{ include "acjs.fullname" . }}-svc
    caBundle: {{ $cert.Cert | b64enc }}
  admissionReviewVersions: ["v1"]
  sideEffects: None
  timeoutSeconds: 15
